# Generated by Django 2.0.4 on 2018-04-22 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datapoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_point', models.IntegerField()),
                ('layout_x', models.IntegerField()),
                ('layout_y', models.IntegerField()),
                ('rssi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_title', models.CharField(max_length=50)),
                ('layout_owner', models.CharField(max_length=50)),
                ('layout_size_x', models.IntegerField()),
                ('layout_size_y', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='datapoints',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotspot.Layout'),
        ),
    ]
