# Generated by Django 2.0.4 on 2018-05-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='layout_image',
            field=models.ImageField(upload_to='layouts/'),
        ),
    ]
